In [1]:
from sklearn import datasets

In [2]:
boston=datasets.load_boston()

In [3]:
x=boston.data
y=boston.target

In [4]:
import pandas as pd
boston_data=pd.DataFrame(x,columns=boston.feature_names)
boston_data.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1)

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
reg=LinearRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)

In [9]:
reg.score(x_test,y_test)

0.7836295385076281

# MultiVariable Linear Regression

In [10]:
for i in boston.feature_names:
    new_f=i+'*'+i
    boston_data[new_f]=boston_data[i]**2
boston_data.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,CHAS*CHAS,NOX*NOX,RM*RM,AGE*AGE,DIS*DIS,RAD*RAD,TAX*TAX,PTRATIO*PTRATIO,B*B,LSTAT*LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,...,0.0,0.289444,43.230625,4251.04,16.728100,1.0,87616.0,234.09,157529.6100,24.8004
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,...,0.0,0.219961,41.229241,6225.21,24.672082,4.0,58564.0,316.84,157529.6100,83.5396
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,...,0.0,0.219961,51.624225,3733.21,24.672082,4.0,58564.0,316.84,154315.4089,16.2409
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,...,0.0,0.209764,48.972004,2097.64,36.750269,9.0,49284.0,349.69,155732.8369,8.6436
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,...,0.0,0.209764,51.079609,2937.64,36.750269,9.0,49284.0,349.69,157529.6100,28.4089
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,...,0.0,0.209764,41.344900,3445.69,36.750269,9.0,49284.0,349.69,155330.5744,27.1441
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,...,0.0,0.274576,36.144144,4435.56,30.919160,25.0,96721.0,231.04,156499.3600,154.5049
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,...,0.0,0.274576,38.093584,9235.21,35.408450,25.0,96721.0,231.04,157529.6100,366.7225
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,...,0.0,0.274576,31.708161,10000.00,36.991940,25.0,96721.0,231.04,149482.7569,895.8049
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,...,0.0,0.274576,36.048016,7378.81,43.455782,25.0,96721.0,231.04,149544.6241,292.4100

In [11]:
x=boston_data.values
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=1)

In [12]:
reg_1=LinearRegression()
reg_1.fit(x_train,y_train)
y_pred=reg_1.predict(x_test)

In [13]:
reg_1.score(x_test,y_test)

0.8787006807787356